export var plumberGeneral = [
  {
    "questionNo": 1,
    "Question": "Identify the fixture used for hot and cold water supply?",
    "option_a": "Wall Mixture",
    "option_b": "Pedestal Faucet",
    "option_c": "Geyser Mixture",
    "option_d": "A & C",
    "Answer": "A",
    "marathiQuestion": "गरम आणि थंड पाण्याचा पुरवठा करण्यासाठी वापरलेले फिक्स्चर ओळखा?",
    "marathi_option_a": "दीवार मिश्रण",
    "marathi_option_b": "कुरसी नल",
    "marathi_option_c": "गीजर मिश्रण",
    "marathi_option_d": "A & C",
    "Marks": 2.5
  },
  {
    "questionNo": 2,
    "Question": "What is the maximum diameter of stoneware pipe?",
    "option_a": "300mm",
    "option_b": "400mm",
    "option_c": "500mm",
    "option_d": "800mm",
    "Answer": "D",
    "marathiQuestion": "स्टोनवेअर पाईपचा जास्तीत जास्त व्यास किती आहे?",
    "marathi_option_a": "300mm",
    "marathi_option_b": "400mm",
    "marathi_option_c": "500mm",
    "marathi_option_d": "800mm",
    "Marks": 2.5
  },
  {
    "questionNo": 3,
    "Question": "Which thread patterns is used in standard pipe fittings?",
    "option_a": "BSW",
    "option_b": "BSP",
    "option_c": "BSF",
    "option_d": "B.A",
    "Answer": "B",
    "marathiQuestion": "मानक पाईप फिटिंग्जमध्ये कोणते थ्रेड पॅटर्न वापरले जातात?",
    "marathi_option_a": "BSW",
    "marathi_option_b": "BSP",
    "marathi_option_c": "BSF",
    "marathi_option_d": "B.A",
    "Marks": 2.5
  },
  {
    "questionNo": 4,
    "Question": "What is the use of end caps",
    "option_a": "To protect the pipe end",
    "option_b": "for bend the pipe",
    "option_c": "joints two pipe",
    "option_d": "For maintenance purpose",
    "Answer": "A",
    "marathiQuestion": "एंड कॅपचा उपयोग काय आहे",
    "marathi_option_a": "पाईपचे टोक संरक्षित करण्यासाठी",
    "marathi_option_b": "पाईप वाकणे",
    "marathi_option_c": "दोन पाईप्स जोडते",
    "marathi_option_d": "देखरेखीच्या उद्देशाने",
    "Marks": 2.5
  },
  {
    "questionNo": 5,
    "Question": "Lead Caulked joints are provided in which pipe?",
    "option_a": "G.I Pipe",
    "option_b": "R.C.C Pipe",
    "option_c": "C.I Pipe",
    "option_d": "PVC Pipe",
    "Answer": "C",
    "marathiQuestion": "कोणत्या पाईपमध्ये शिशाचे जोडलेले सांधे बसवले जातात?",
    "marathi_option_a": "जी.आई पाइप",
    "marathi_option_b": "आर.सी.सी पाइप",
    "marathi_option_c": "सी.आई पाइप",
    "marathi_option_d": "पीवीसी पाइप",
    "Marks": 2.5
  },
  {
    "questionNo": 6,
    "Question": "Pipe cutting die is generally used for?",
    "option_a": "Divided the pipe into four parts",
    "option_b": "To bend the pipe",
    "option_c": "Divided the pipe into three parts",
    "option_d": "For threading only",
    "Answer": "D",
    "marathiQuestion": "पाईप कटिंग डायज सामान्यतः कशासाठी वापरतात?",
    "marathi_option_a": "पाईपचे चार भाग करा",
    "marathi_option_b": "पाईप वाकणे",
    "marathi_option_c": "पाईपचे तीन भाग केले",
    "marathi_option_d": "फक्त थ्रेडिंगसाठी",
    "Marks": 2.5
  },
  {
    "questionNo": 7,
    "Question": "Which valve prevents flow of water in both the directions?",
    "option_a": "Check Valve",
    "option_b": "Gate Valve",
    "option_c": "Shutoff wall",
    "option_d": "Globe Valve",
    "Answer": "A",
    "marathiQuestion": "कोणता झडपा पाण्याचा प्रवाह दोन्ही दिशांना थांबवतो?",
    "marathi_option_a": "वाल्व जांचें",
    "marathi_option_b": "गेट वाल्व",
    "marathi_option_c": "शटऑफ़ दीवार",
    "marathi_option_d": "Globe वाल्व",
    "Marks": 2.5
  },
  {
    "questionNo": 8,
    "Question": "Which connector can be used for connecting pipes of different diameters",
    "option_a": "Tee",
    "option_b": "Female Adaptor",
    "option_c": "Cross Tee",
    "option_d": "Elbow",
    "Answer": "D",
    "marathiQuestion": "वेगवेगळ्या व्यासाचे पाईप्स जोडण्यासाठी कोणता कनेक्टर वापरला जाऊ शकतो?",
    "marathi_option_a": "Tee",
    "marathi_option_b": "महिला अनुकूलक",
    "marathi_option_c": "Cross Tee",
    "marathi_option_d": "Elbow",
    "Marks": 2.5
  },
  {
    "questionNo": 9,
    "Question": "The Layers of composite pipes are?",
    "option_a": "Polyethylene, Aluminum and polyethylene respectively.",
    "option_b": "Polyethylene, fibber and polyethylene respectively.",
    "option_c": "Fibber, Aluminum and polyethylene respectively.",
    "option_d": "Aluminum, Fibber, polyethylene respectively.",
    "Answer": "A",
    "marathiQuestion": "संमिश्र पाईप्सचे स्तर काय आहेत?",
    "marathi_option_a": "पॉलिथिन, ॲल्युमिनियम आणि पॉलिथिलीन.",
    "marathi_option_b": "पॉलिथिलीन, फायबर आणि पॉलिथिलीन",
    "marathi_option_c": "फायबर, ॲल्युमिनियम आणि पॉलिथिलीन.",
    "marathi_option_d": "ॲल्युमिनियम, फायबर, पॉलिथिलीन.",
    "Marks": 2.5
  },
  {
    "questionNo": 10,
    "Question": "Which meter issued to check the quantity of water supplied to a house?",
    "option_a": "Water meter",
    "option_b": "Energy meter",
    "option_c": "Pressure Gauge",
    "option_d": "Flow control meter",
    "Answer": "A",
    "marathiQuestion": "घराला किती पाणी पुरवठा केला जातो हे तपासण्यासाठी वॉटर मीटर जारी केले जाते?",
    "marathi_option_a": "पाणी मीटर",
    "marathi_option_b": "ऊर्जा मीटर",
    "marathi_option_c": "दबाव मापक",
    "marathi_option_d": "प्रवाह नियंत्रण मीटर",
    "Marks": 2.5
  },
  {
    "questionNo": 11,
    "Question": "Flanged joint are capable for ?",
    "option_a": "Where it may be lay underground",
    "option_b": "Where it may be occasionally dismantle or reassembling",
    "option_c": "Where it may be bear vibrations or deflections of pipe",
    "option_d": "Where it may be bear high velocity of flow",
    "Answer": "B",
    "marathiQuestion": "फ्लैंज्ड सांधे काय सक्षम आहेत?",
    "marathi_option_a": "जिथे ते जमिनीखाली साठवले जाऊ शकते",
    "marathi_option_b": "जेथे ते कधीकधी मोडून काढले किंवा पुन्हा एकत्र केले जाऊ शकते",
    "marathi_option_c": "जेथे ते पाईपचे कंपन किंवा विक्षेपण सहन करू शकते",
    "marathi_option_d": "जेथे तो प्रवाहाचा उच्च वेग सहन करू शकतो",
    "Marks": 2.5
  },
  {
    "questionNo": 12,
    "Question": "How do you decide the size of water pump in a pump house?",
    "option_a": "An estimated population",
    "option_b": "Quantity of water available",
    "option_c": "The catchment area",
    "option_d": "All of the above",
    "Answer": "D",
    "marathiQuestion": "पंप हाऊसमधील पाण्याच्या पंपाचा आकार कसा काढता?",
    "marathi_option_a": "अंदाजे लोकसंख्या",
    "marathi_option_b": "उपलब्ध पाण्याचे प्रमाण",
    "marathi_option_c": "पाणलोट क्षेत्र",
    "marathi_option_d": "पाण्याचे प्रमाण",
    "Marks": 2.5
  },
  {
    "questionNo": 13,
    "Question": "By which of the following tool we can joint to HDPE pipe?",
    "option_a": "Shaddel",
    "option_b": "Ferrule",
    "option_c": "Tee",
    "option_d": "Socket",
    "Answer": "D",
    "marathiQuestion": "खालीलपैकी कोणत्या साधनाने आपण HDPE पाईप्स जोडू शकतो?",
    "marathi_option_a": "शेडल",
    "marathi_option_b": "फेरूल",
    "marathi_option_c": "Tee",
    "marathi_option_d": "सॉकेट",
    "Marks": 2.5
  },
  {
    "questionNo": 14,
    "Question": "Which type of PVC pipe used for hot water supply",
    "option_a": "PVC pipe",
    "option_b": "CPVC Pipe",
    "option_c": "G I pipe",
    "option_d": "Cast Iron Pipe",
    "Answer": "B",
    "marathiQuestion": "गरम पाणी पुरवठ्यासाठी कोणत्या प्रकारचे पीव्हीसी पाईप वापरले जातात?",
    "marathi_option_a": "पीवीसी पाइप",
    "marathi_option_b": "सीपीवीसी पाइप",
    "marathi_option_c": "जी.आई पाइप",
    "marathi_option_d": "कास्ट लोह पाईप",
    "Marks": 2.5
  },
  {
    "questionNo": 15,
    "Question": "Where do you fix the foot valve",
    "option_a": "Top of suction pipe",
    "option_b": "In suction and delivery pipes",
    "option_c": "Bottom of suction type",
    "option_d": "To Darin out water from suction",
    "Answer": "C",
    "marathiQuestion": "आपण पाऊल झडप कुठे ठीक करू?",
    "marathi_option_a": "सक्शन पाईपच्या वर",
    "marathi_option_b": "सक्शन आणि डिलिव्हरी पाईप्समध्ये",
    "marathi_option_c": "सक्शन प्रकार अंतर्गत",
    "marathi_option_d": "सक्शनने पाणी काढणे",
    "Marks": 2.5
  },
  {
    "questionNo": 16,
    "Question": "What is the depth of underground water supply Pipe line?",
    "option_a": "2 Meter",
    "option_b": "1.5 Meter",
    "option_c": "1.Meter",
    "option_d": "All of the above",
    "Answer": "D",
    "marathiQuestion": "भूमिगत पाणीपुरवठा पाईपलाईनची खोली किती आहे?",
    "marathi_option_a": "2 मीटर",
    "marathi_option_b": "1.5 मीटर",
    "marathi_option_c": "1.मीटर",
    "marathi_option_d": "3 मीटर",
    "Marks": 2.5
  },
  {
    "questionNo": 17,
    "Question": "Which tool we use for cutting and threading of G I pipe?",
    "option_a": "Hexa Blade",
    "option_b": "Copper Cutter",
    "option_c": "Die Set",
    "option_d": "All of these",
    "Answer": "C",
    "marathiQuestion": "जीआय पाईप कापण्यासाठी आणि थ्रेडिंगसाठी आपण कोणते साधन वापरतो?",
    "marathi_option_a": "हेक्सा ब्लेड",
    "marathi_option_b": "तांबे कटर",
    "marathi_option_c": "डायर",
    "marathi_option_d": "या सर्व",
    "Marks": 2.5
  },
  {
    "questionNo": 18,
    "Question": "Which materials is used for drainage pipe line?",
    "option_a": "Brass pipe",
    "option_b": "G I pipe",
    "option_c": "Steel pipe",
    "option_d": "Ceramic pipe",
    "Answer": "D",
    "marathiQuestion": "ड्रेनेज पाईप लाईनसाठी कोणती सामग्री वापरली जाते?",
    "marathi_option_a": "पितळ पाईप",
    "marathi_option_b": "जी.आई पाइप",
    "marathi_option_c": "लोह के नल",
    "marathi_option_d": "सिरेमिक पाइप",
    "Marks": 2.5
  },
  {
    "questionNo": 19,
    "Question": "What is the use of P trap",
    "option_a": "The P-trap traps solids that can clog the drain or sewer line",
    "option_b": "To stops sewer gases from backing  your home",
    "option_c": "Not used in Plumbing System",
    "option_d": "A&B",
    "Answer": "D",
    "marathiQuestion": "पी ट्रैप उपयोग काय आहे?",
    "marathi_option_a": "पी-ट्रॅप सापळे घन पदार्थांना अडकवतात जे ड्रेन किंवा सीवर लाइन अडवू शकतात",
    "marathi_option_b": "गटारातील वायू तुमच्या घरात पसरण्यापासून रोखण्यासाठी",
    "marathi_option_c": "प्लंबिंग सिस्टममध्ये वापरले जात नाही",
    "marathi_option_d": "A&B",
    "Marks": 2.5
  },
  {
    "questionNo": 20,
    "Question": "What test is applied to check the alignment and condition of the inside of the pipes?",
    "option_a": "Smoke test",
    "option_b": "Hydrostatic test",
    "option_c": "Pneumatic test",
    "option_d": "Mirror test",
    "Answer": "B",
    "marathiQuestion": "पाईप्सच्या आतील संरेखन आणि स्थिती तपासण्यासाठी कोणती चाचणी लागू केली जाते?",
    "marathi_option_a": "धूर चाचणी",
    "marathi_option_b": "हायड्रोस्टॅटिक चाचणी",
    "marathi_option_c": "वायवीय चाचणी",
    "marathi_option_d": "मिरर चाचणी",
    "Marks": 2.5
  },
  {
    "questionNo": 21,
    "Question": "Why water seal is required in a trap?",
    "option_a": "To allow the passage of waste water",
    "option_b": "To prevent the follow of waste water",
    "option_c": "To prevent the passage of foul gases from the drain",
    "option_d": "To block the soil Passage",
    "Answer": "C",
    "marathiQuestion": "ट्रैप में वॉटर सील का आवश्यक आहे?",
    "marathi_option_a": "कचरा पाण्याचा निचरा होण्यासाठी",
    "marathi_option_b": "वाया जाणारे पाणी थांबवण्यासाठी",
    "marathi_option_c": "गलिच्छ वायू नाल्यातून बाहेर पडण्यापासून प्रतिबंधित करणे",
    "marathi_option_d": "चिखलाचा रस्ता अडवायचा",
    "Marks": 2.5
  },
  {
    "questionNo": 22,
    "Question": "C I Drainage  pipe is not joint with?",
    "option_a": "Spun yarn & lead jointly",
    "option_b": "Cement  motor with spun yarn",
    "option_c": "In seal",
    "option_d": "Compression gaskets",
    "Answer": "A",
    "marathiQuestion": "सीआय ड्रेनेज पाईपला जोडलेले नाही?",
    "marathi_option_a": "सूत कातले आणि आघाडी संयुक्तपणे",
    "marathi_option_b": "कातलेल्या धाग्यासह सिमेंट मोटर",
    "marathi_option_c": "In seal",
    "marathi_option_d": "कॉम्प्रेशन गॅस्केट",
    "Marks": 2.5
  },
  {
    "questionNo": 23,
    "Question": "For drainage pipes in building the test applied before putting them to use is for?",
    "option_a": "Water Test",
    "option_b": "Smoke Test",
    "option_c": "Straightness test",
    "option_d": "All of these",
    "Answer": "A",
    "marathiQuestion": "इमारतीच्या बांधकामात ड्रेनेज पाईप्स वापरण्यापूर्वी त्यांची चाचणी का केली जाते?",
    "marathi_option_a": "पाणी चाचणी",
    "marathi_option_b": "धूर चाचणी",
    "marathi_option_c": "सरळपणा चाचणी",
    "marathi_option_d": "या सर्व",
    "Marks": 2.5
  },
  {
    "questionNo": 24,
    "Question": "What is the standard size of inspection chamber in drainage system?",
    "option_a": "200x200 mm",
    "option_b": "500x500 mm",
    "option_c": "315mm & 600mm",
    "option_d": "600x600 mm",
    "Answer": "C",
    "marathiQuestion": "ड्रेनेज सिस्टीममध्ये तपासणी चेंबरचा मानक आकार किती आहे?",
    "marathi_option_a": "200x200 mm",
    "marathi_option_b": "500x500 mm",
    "marathi_option_c": "315mm & 600mm",
    "marathi_option_d": "600x600 mm",
    "Marks": 2.5
  },
  {
    "questionNo": 25,
    "Question": "The pipe receiving discharge from water closet urinal etc. are called",
    "option_a": "Waste pipe",
    "option_b": "Soil pipe",
    "option_c": "Rain water",
    "option_d": "Ventilation Pipe",
    "Answer": "B",
    "marathiQuestion": "पाण्याच्या कपाट, मूत्रालय इत्यादींमधून सांडपाणी ग्रहण करणारे पाईप म्हणतातI",
    "marathi_option_a": "कचरा पाईप",
    "marathi_option_b": "चिकणमाती पाईप",
    "marathi_option_c": "पावसाचे पाणी",
    "marathi_option_d": "वायुवीजन पाईप",
    "Marks": 2.5
  },
  {
    "questionNo": 26,
    "Question": "Commode is known as",
    "option_a": "Urinal",
    "option_b": "EWC",
    "option_c": "LWC",
    "option_d": "Sink",
    "Answer": "B",
    "marathiQuestion": "कमोड म्हणतात",
    "marathi_option_a": "Urinal",
    "marathi_option_b": "EWC",
    "marathi_option_c": "LWC",
    "marathi_option_d": "Sink",
    "Marks": 2.5
  },
  {
    "questionNo": 27,
    "Question": "What is the shape of the septic tank?",
    "option_a": "Square shape",
    "option_b": "Rectangular",
    "option_c": "Circular",
    "option_d": "Oval",
    "Answer": "B",
    "marathiQuestion": "सेप्टिक टाकीचा आकार काय आहे?",
    "marathi_option_a": "चौरस आकार",
    "marathi_option_b": "आयताकृती",
    "marathi_option_c": "परिपत्रक",
    "marathi_option_d": "Oval",
    "Marks": 2.5
  },
  {
    "questionNo": 28,
    "Question": "Which is the place preferred to fix scour ?",
    "option_a": "Lowest point in pipe line",
    "option_b": "Higher point in pipe line",
    "option_c": "Straight point in pipe line",
    "option_d": "None of these",
    "Answer": "A",
    "marathiQuestion": "डाग बरे करण्यासाठी पसंतीचे ठिकाण कोणते आहे?",
    "marathi_option_a": "पाइपलाइनमधील सर्वात कमी बिंदू",
    "marathi_option_b": "पाइपलाइनमधील उच्च बिंदू",
    "marathi_option_c": "पाइपलाइनमधील सरळ बिंदू",
    "marathi_option_d": "यापैकी काहीही नाही",
    "Marks": 2.5
  },
  {
    "questionNo": 29,
    "Question": "Which test is applied in underground drains and soundness?",
    "option_a": "Hydraulic test",
    "option_b": "Pneumatic test",
    "option_c": "Water test",
    "option_d": "Sound test",
    "Answer": "C",
    "marathiQuestion": "भूमिगत नाले आणि मजबुतीकरण मध्ये कोणती चाचणी केली जाते?",
    "marathi_option_a": "हायड्रॉलिक चाचणी",
    "marathi_option_b": "वायवीय चाचणी",
    "marathi_option_c": "पाणी चाचणी",
    "marathi_option_d": "आवाज चाचणी",
    "Marks": 2.5
  },
  {
    "questionNo": 30,
    "Question": "By which tool we can check fitting level of Washbasin?",
    "option_a": "Sprit level",
    "option_b": "Vernier caliper",
    "option_c": "Measurement tap",
    "option_d": "Scale",
    "Answer": "A",
    "marathiQuestion": "कोणत्या उपकरणाने आपण वॉश बेसिनची फिटिंग पातळी तपासू शकतो?",
    "marathi_option_a": "Sprit level",
    "marathi_option_b": "Vernier caliper",
    "marathi_option_c": "Measurement tap",
    "marathi_option_d": "Scale",
    "Marks": 2.5
  },
  {
    "questionNo": 31,
    "Question": "What should be the length of  drainage line's Slope?",
    "option_a": "10 MM",
    "option_b": "5 MM",
    "option_c": "2 MM",
    "option_d": "4 MM",
    "Answer": "A",
    "marathiQuestion": "ड्रेनेज लाईनच्या उताराची लांबी किती असावी?",
    "marathi_option_a": "10 MM",
    "marathi_option_b": "5 MM",
    "marathi_option_c": "2 MM",
    "marathi_option_d": "4 MM",
    "Marks": 2.5
  },
  {
    "questionNo": 32,
    "Question": "Which materials is used for joining CI pipe?",
    "option_a": "Lead and cement",
    "option_b": "Lead and lead wool",
    "option_c": "Zink and lead wool",
    "option_d": "Copper and hemp yarn",
    "Answer": "B",
    "marathiQuestion": "सीआय पाईप मध्ये सामील होण्यासाठी कोणती सामग्री वापरली जाते?",
    "marathi_option_a": "शिसे आणि सिमेंट",
    "marathi_option_b": "शिसे आणि शिसे लोकर",
    "marathi_option_c": "जस्त आणि शिसे लोकर",
    "marathi_option_d": "तांबे आणि भांग धागा",
    "Marks": 2.5
  },
  {
    "questionNo": 33,
    "Question": "What is used at the junction of house sewer and municipal sewer?",
    "option_a": "Nani trap",
    "option_b": "P Trap",
    "option_c": "Q trap",
    "option_d": "Intercepting Trap",
    "Answer": "D",
    "marathiQuestion": "घरगुती गटार आणि नगरपालिका गटार यांच्या जंक्शनवर कोणता वापरला जातो?",
    "marathi_option_a": "Nani trap",
    "marathi_option_b": "P Trap",
    "marathi_option_c": "Q trap",
    "marathi_option_d": "Intercepting Trap",
    "Marks": 2.5
  },
  {
    "questionNo": 34,
    "Question": "Which pipe fitting is used to connect service pipe into a main water line?",
    "option_a": "Adjusting nut",
    "option_b": "Ferrule",
    "option_c": "Coupling",
    "option_d": "Air valve",
    "Answer": "B",
    "marathiQuestion": "मुख्य पाण्याच्या लाईनला सर्व्हिस पाईप जोडण्यासाठी कोणत्या पाईप फिटिंगचा वापर केला जातो?",
    "marathi_option_a": "नट समायोजित करणे",
    "marathi_option_b": "फेरूल",
    "marathi_option_c": "कपलिंग",
    "marathi_option_d": "Air valve",
    "Marks": 2.5
  },
  {
    "questionNo": 35,
    "Question": "What we use to joint CPVC pipe?",
    "option_a": "Solvent cement",
    "option_b": "Pussfit joint",
    "option_c": "Heat fusion",
    "option_d": "screwed schedule",
    "Answer": "A",
    "marathiQuestion": "CPVC पाईप्स जोडण्यासाठी आम्ही काय वापरतो?",
    "marathi_option_a": "Solvent cement",
    "marathi_option_b": "Pussfit joint",
    "marathi_option_c": "Heat fusion",
    "marathi_option_d": "screwed schedule",
    "Marks": 2.5
  },
  {
    "questionNo": 36,
    "Question": "Over flow from a tank is controlled by?",
    "option_a": "Gate value",
    "option_b": "Ball value",
    "option_c": "Float value",
    "option_d": "Check value",
    "Answer": "C",
    "marathiQuestion": "टाकीमधून ओव्हर फ्लो नियंत्रित केला जातो?",
    "marathi_option_a": "Gate value",
    "marathi_option_b": "Ball value",
    "marathi_option_c": "Foot value",
    "marathi_option_d": "Check value",
    "Marks": 2.5
  },
  {
    "questionNo": 37,
    "Question": "What is used for prevent Leakage?",
    "option_a": "Taflon Tape",
    "option_b": "Solvent",
    "option_c": "M Seal",
    "option_d": "A & B",
    "Answer": "D",
    "marathiQuestion": "गळती थांबवण्यासाठी काय वापरले जाते?",
    "marathi_option_a": "Taflon Tape",
    "marathi_option_b": "Solvent",
    "marathi_option_c": "M Seal",
    "marathi_option_d": "A & B",
    "Marks": 2.5
  },
  {
    "questionNo": 38,
    "Question": "What are the methods to installing G I pipe?",
    "option_a": "Pipe cutting",
    "option_b": "Deburr",
    "option_c": "Fitting using Teflon tapes",
    "option_d": "All of these",
    "Answer": "D",
    "marathiQuestion": "GI पाईप बसवण्याच्या पद्धती काय आहेत?",
    "marathi_option_a": "पाईप कटिंग",
    "marathi_option_b": "Deburr",
    "marathi_option_c": "टेफ्लॉन टेप वापरून फिटिंग",
    "marathi_option_d": "या सर्व",
    "Marks": 2.5
  },
  {
    "questionNo": 39,
    "Question": "The following are part of water supply system in a house",
    "option_a": "Underground Tank",
    "option_b": "Overhead Tank",
    "option_c": "Pipes, fittings and valves",
    "option_d": "All the above",
    "Answer": "D",
    "marathiQuestion": "घरातील पाणीपुरवठा यंत्रणेचे खालील भाग आहेत",
    "marathi_option_a": "भूमिगत टाकी",
    "marathi_option_b": "ओवरहेड टैंक",
    "marathi_option_c": "पाईप्स, फिटिंग्ज आणि वाल्व",
    "marathi_option_d": "वरील सर्व",
    "Marks": 2.5
  },
  {
    "questionNo": 40,
    "Question": "Hydrant is provided for?",
    "option_a": "Irrigation purpose",
    "option_b": "Fire fighting purpose",
    "option_c": "Drinking purpose",
    "option_d": "Washing purpose",
    "Answer": "B",
    "marathiQuestion": "हायड्रंटची व्यवस्था केली आहे का?",
    "marathi_option_a": "सिंचनाचा उद्देश",
    "marathi_option_b": "अग्निशमन उद्देश",
    "marathi_option_c": "पिण्याचा उद्देश",
    "marathi_option_d": "धुण्याचा उद्देश",
    "Marks": 2.5
  },
  {
    "questionNo": 41,
    "Question": "Which jacket is used for traffic control ?",
    "option_a": "Reflecting jacket",
    "option_b": "winter jacket",
    "option_c": "Protection jacket",
    "option_d": "Non of these",
    "Answer": "A",
    "marathiQuestion": "वाहतूक नियंत्रणासाठी कोणते जॅकेट वापरले जाते?",
    "marathi_option_a": "परावर्तित जाकीट",
    "marathi_option_b": "हिवाळ्यातील जाकीट",
    "marathi_option_c": "सुरक्षा जाकीट",
    "marathi_option_d": "यापैकी काहीही नाही",
    "Marks": 2.5
  },
  {
    "questionNo": 42,
    "Question": "Workplace related injuries, illnesses and deaths impose costs upon?",
    "option_a": "Employers",
    "option_b": "Employees",
    "option_c": "The community",
    "option_d": "All of the above",
    "Answer": "A",
    "marathiQuestion": "कामाच्या ठिकाणाशी संबंधित दुखापती, आजार आणि मृत्यूची किंमत कोण घेते?",
    "marathi_option_a": "Employers",
    "marathi_option_b": "Employees",
    "marathi_option_c": "The community",
    "marathi_option_d": "वरील सर्व",
    "Marks": 2.5
  },
  {
    "questionNo": 43,
    "Question": "What is the first step in hazard control",
    "option_a": "Elimination",
    "option_b": "Identification",
    "option_c": "Engineering control",
    "option_d": "Speeding awareness",
    "Answer": "B",
    "marathiQuestion": "धोका नियंत्रणाची पहिली पायरी काय आहे?",
    "marathi_option_a": "Elimination",
    "marathi_option_b": "पहचान",
    "marathi_option_c": "अभियांत्रिकी नियंत्रणे",
    "marathi_option_d": "जागरूकता वाढणे",
    "Marks": 2.5
  },
  {
    "questionNo": 44,
    "Question": "Which is  not a part of PPE'S",
    "option_a": "Shoes",
    "option_b": "Helmat",
    "option_c": "Life Jacket",
    "option_d": "Pen",
    "Answer": "D",
    "marathiQuestion": "जो PPE'S चा भाग नाही",
    "marathi_option_a": "Shoes",
    "marathi_option_b": "Helmat",
    "marathi_option_c": "Life Jacket",
    "marathi_option_d": "Pen",
    "Marks": 2.5
  }
];
